name: Check typos

on:
  push:
    branches:
      - main
    paths:
      - "**.md"
      - ".github/workflows/**"
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - "**.md"
      - ".github/workflows/**"

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: typos
        uses: crate-ci/typos@5374cbf686e897b15713110e233094e2874de7ef # v1.46.1
